app:
  namespace: weather-bot-prod

replicas: 2

config:
  DEBUG: "false"
  LOG_LEVEL: "ERROR"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

service:
  type: LoadBalancer
