apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }}-sa
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if .Values.iam.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iam.roleArn }}
  {{- end }}

