apiVersion: v1
kind: Service
metadata:
  name: weather-bot-service
  namespace: weather-bot
  labels:
    app: weather-bot
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: weather-bot