@echo off
echo Deploying infrastructure for demonstration...
cd terraform/environments/dev
echo Initializing Terraform...
terraform init
echo Applying infrastructure...
terraform apply -auto-approve
echo Infrastructure deployed. Remember to run cleanup-demo.bat when finished.
pause
