apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-scraper
  namespace: whatsapp-scraper
  labels:
    app: whatsapp-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-scraper
  template:
    metadata:
      labels:
        app: whatsapp-scraper
    spec:
      containers:
      - name: whatsapp-scraper
        image: whatsapp-scraper:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: whatsapp-scraper-config
        - secretRef:
            name: whatsapp-scraper-secrets
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5