# WhatsApp Weather Bot Helm Chart Values
# This file contains default values for the weather bot deployment on EKS

app:
  name: weather-bot
  namespace: weather-bot

# Container image configuration
image:
  # ECR repository URL - will be set during deployment via --set flag
  repository: ""  # e.g., "123456789012.dkr.ecr.region.amazonaws.com/weather-bot"
  tag: "latest"
  pullPolicy: Always

# Init container removed - using IRSA for Parameter Store access directly

# Kubernetes service configuration
service:
  type: ClusterIP  # Changed from NodePort - ALB will handle external access
  port: 80
  targetPort: 8000

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Number of replicas
replicas: 2  # Increased for HA

# Application configuration (non-sensitive)
config:
  DEBUG: "false"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  LOG_LEVEL: "INFO"
  ENABLE_METRICS: "true"
  DATABASE_URL: "sqlite:///./data/weather_bot.db"

# Secrets are now loaded directly from AWS Parameter Store via IRSA

# Ingress configuration for ALB
ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
  hosts:
    - host: ""  # Will be set to ALB DNS name
      paths:
        - path: /
          pathType: Prefix

# Health checks
healthcheck:
  path: /health
  liveness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5

# IAM configuration for IRSA
iam:
  roleArn: ""  # Will be set during deployment, e.g., "arn:aws:iam::123456789012:role/weather-bot-parameter-store-role"

# AWS configuration
aws:
  region: ""  # Will be set during deployment, e.g., "us-east-1"

# Labels applied to all resources
labels:
  project: weather-bot
  environment: production
  managedBy: helm