app:
  name: weather-bot
  namespace: weather-bot

image:
  repository: weather-bot
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

replicas: 1

config:
  DEBUG: "false"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  APP_NAME: "WhatsApp Weather Bot"
  LOG_LEVEL: "INFO"

secrets:
  TWILIO_ACCOUNT_SID: "your_account_sid_here"
  TWILIO_AUTH_TOKEN: "your_auth_token_here"
  TWILIO_WHATSAPP_FROM: "whatsapp:+14155238886"

labels:
  project: weather-bot
  version: v1.0.0